### ISSUE TITLE
国内 ( 可能 ) 无法进行主题更新

### ISSUE THREAD

**Issue by FlyingSky-CN** [FlyingSky-CN/MDr#38]
由于对 `raw.githubusercontent.com` 的访问限制，在中国大陆部署的主题会有无法进行一键更新的情况。

**Comment by paizi** [comment]
看起来jsDelivr只会识别被发布的版本

**Comment by FlyingSky-CN** [comment]
> 看起来jsDelivr只会识别被发布的版本

那就... 正式版和测试版分开好了
