### ISSUE TITLE
插件短代码

### ISSUE THREAD

**Issue by Zynismus16** [FlyingSky-CN/MDr#66]
如题，使用该主题后无法使用其他插件的短代码。
是主题本身限制还是插件不受支持。我该修改那个文件。

在此感谢开发大大的辛勤付出与无私奉献。

**Comment by FlyingSky-CN** [comment]
你不妨将 [./functions.php L5](https://github.com/FlyingSky-CN/MDr/blob/0aab69a03fff8d3b98b3d041aaad3f97744f7f95/functions.php#L5) 注释掉试一试，这里考虑插件是不是用了和主题同样的接口导致冲突。

**Comment by Zynismus16** [comment]
我参照[./functions.php L5](https://github.com/FlyingSky-CN/MDr/blob/0aab69a03fff8d3b98b3d041aaad3f97744f7f95/functions.php#L5)的内容查看了问题插件的代码，发现它的调用方式如下
```
Typecho_Plugin::factory('Widget_Abstract_Contents')->filter = array('APlayer_Plugin','playerfilter');
        Typecho_Plugin::factory('Widget_Abstract_Contents')->contentEx = array('APlayer_Plugin','playerparse');
        Typecho_Plugin::factory('Widget_Abstract_Contents')->excerptEx = array('APlayer_Plugin','playerparse');
        Typecho_Plugin::factory('Widget_Archive')->header = array('APlayer_Plugin','playercss');
        Typecho_Plugin::factory('Widget_Archive')->footer = array('APlayer_Plugin','footerjs');
```
将主题调用代码注释后仍不起作用。
该示例插件为
[https://github.com/FaithPatrick/APlayer-Typecho-Plugin](https://github.com/FaithPatrick/APlayer-Typecho-Plugin)

使用方式为在文章中写入[player id="*****"/]来调用插件。

问题描述：
在文章中调用短代码后，前台无法看到该代码，并非直接显示该代码

我认为是主题文件  [ShortCode.php](https://github.com/FlyingSky-CN/MDr/blob/0aab69a03fff8d3b98b3d041aaad3f97744f7f95/core/lib/ShortCode.php) 或者 [Main.php](https://github.com/FlyingSky-CN/MDr/blob/0aab69a03fff8d3b98b3d041aaad3f97744f7f95/core/lib/Main.php) ，未定义该短代码，并设置无法识别的短代码默认不显示导致的。
奈何隔行如隔山，本人只会简单修改代码而无法读懂代码。特此求助。

**Comment by FlyingSky-CN** [comment]
需要注意的一点是，MDr 的短代码解析是按需查询，对于未定义的短代码是不会做处理的，理论如此并且实测如此（见图中 undefined 标签会直接输出）。

以及咱为了明确问题实际上手测试发现无法复现这个问题，MDr 和 APlayer 的短代码都可以正常解析（测试结果见图），所以咱考虑是否为您插件的配置或使用的问题。

![image](https://user-images.githubusercontent.com/29764514/176625142-9b1a4c04-842d-42f4-b4fb-bc046d2cafe7.png)

由于问题无法复现，故关闭这个 issue，但如有后续问题也欢迎跟进及 reopen。

    测试环境：
    PHP version: 7.4.13
    Typecho version: release v1.2.0
    MDr version: petals v0.1
    APlayer: 您提供的仓库的最后一次提交版本
