### ISSUE TITLE
文章缩略图分辨率问题

### ISSUE THREAD

**Issue by RamSong** [FlyingSky-CN/MDr#67]
*这是一个功能请求模板，有助于您理清思路。如果你觉得其中提供的项目多余请删去，比如这一行字。*
## 高分辨率图片显示

电脑端

![pc.png](https://raw.githubusercontent.com/RamSong/Temp/main/Github/Issues/fsky7-issues-1/pc2.png)

手机端

![android.jpg](https://raw.githubusercontent.com/RamSong/Temp/main/Github/Issues/fsky7-issues-1/android.jpg)

可以看到这个分辨率太大会导致这个图片在PC和移动端出问题

## 建议

在编辑文章下加入更多自定义的功能

![new.png](https://raw.githubusercontent.com/RamSong/Temp/main/Github/Issues/fsky7-issues-1/new.png)

**Comment by FlyingSky-CN** [comment]
在 MDr 的设计上，文章封面图的长宽比本就有合适的区间，图片过长竖屏观感不好，图片过宽横屏观感不好。这是一个已知的问题，但是 MDr 并没有强制要求封面图的长宽比，而是交由使用者决定。

为文章封面图对不同的屏幕做出相应的适配或许是必要的，但是咱不是很认同题给的解决方案（指为移动端/电脑端设置不同的封面图），而其中的一个原因是繁琐。

咱的想法是对不同的屏幕设置合适的长宽比，同一张封面图在不同屏幕上由前端裁切至合适的程度。
